### ISSUE TITLE
.custom returns a number

### ISSUE THREAD

**Issue by tandrewnichols** [cosmosio/get-closest#1]
The docs say this: `getCloset.custom("mercure", days, compareLevenshteinDistance); // "mercredi"`, but in the test, you're doing `days[getCloset.custom("mercure", days, compareLevenshteinDistance)];` and in my quick usage, I've observed that .`custom` does indeed return a number and not a string. I haven't looked at the code, but you have the original list, so it seems like it would be easy to return the item at the index instead of the index, and, I would argue, that's likely to be 1) what people would be expecting and 2) what people would want to happen.

**Comment by podefr** [comment]
hey Andrew, thanks for raising this.

The reason why I decided to go with returning the index of the value instead of the value itself is that values may not be unique, whereas the index is. So if you have an array with two or more identical values, you won't know which one is the closest if one of them gets returned.

This may not matter for most use cases but I didn't want to assume that it would be true for 100% of them so erred on the side of caution.

An alternative approach would be to add another method that calls custom(...) and then returns the value at the index instead, so that all use cases are covered. Would that work?

**Comment by tandrewnichols** [comment]
Yeah, and certainly you can work around this as per the test. I do think the docs should reflect that though. It's probably safe to return the string in case of duplicates as it would return the same string in either case, but I don't object to the implementation being what it is. Just the lack of docs :wink:.

**Comment by podefr** [comment]
thanks Andrew, I fixed the documentation for closest, that was a good catch.
